services:
  # DeepRead AI - Aplicación principal
  deepread-ai:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: deepread-ai-main
    ports:
      - "8501:8501"
    volumes:
      # Persistir base de datos vectorial
      - ./chroma_db:/app/chroma_db
      # Persistir datos de sesión
      - ./data:/app/data
    environment:
      # Variables críticas
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      # Configuración optimizada
      - STREAMLIT_THEME_BASE=light
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - deepread-network

# Red para comunicación (simplificada)
networks:
  deepread-network:
    driver: bridge
